#pragma once

#include "nova/Frontend/AST.h"
#include <string>
#include <unordered_map>
#include <vector>

namespace nova {

// Compiler options that gate strictness-related diagnostics. These mirror the
// TypeScript compiler options. The upstream test suite encodes them as
// `// @option` comment directives at the top of each test file (e.g.
// `// @strict`, `// @strictNullChecks`, `// @noImplicitAny`); the baselines
// were generated by the official compiler *applying* those directives. Nova's
// checker reads the directives (via parseCompilerDirectives) so that strict
// features can be gated per-file instead of globally — without gating they
// would cause net-negative regressions on non-strict test files.
struct TypeCheckerOptions {
    bool strict = false;
    bool noImplicitAny = false;
    bool strictNullChecks = false;
    bool strictFunctionTypes = false;
    bool strictBindCallApply = false;
    bool strictPropertyInitialization = false;
    bool noImplicitThis = false;
    bool useUnknownInCatchVariables = false;
    bool alwaysStrict = false;
    bool noUnusedLocals = false;
    bool noUnusedParameters = false;
    bool exactOptionalPropertyTypes = false;
    bool noImplicitReturns = false;
    bool noFallthroughCasesInSwitch = false;
    bool noUncheckedIndexedAccess = false;
};

class TypeChecker {
public:
    explicit TypeChecker(TypeCheckerOptions opts = {});
    bool check(Program& program);
    const std::vector<std::string>& diagnostics() const { return diagnostics_; }
    const TypeCheckerOptions& options() const { return options_; }

private:
    struct FunctionSignature {
        std::vector<std::string> typeParameters;
        std::vector<TypePtr> typeParameterConstraints;
        std::vector<TypePtr> typeParameterDefaults;
        std::vector<TypePtr> parameters;
        TypePtr returnType;
        bool isOverload = false;
    };

    struct GenericTypeDeclaration {
        std::vector<std::string> typeParameters;
        std::vector<TypePtr> constraints;
        std::vector<TypePtr> defaults;
        TypePtr body;
    };

    std::vector<std::unordered_map<std::string, TypePtr>> scopes_;
    std::unordered_map<std::string, FunctionSignature> functions_;
    std::unordered_map<std::string, std::vector<FunctionSignature>> overloads_;
    std::unordered_map<std::string, TypePtr> namedTypes_;
    std::unordered_map<std::string, GenericTypeDeclaration> genericTypes_;
    std::unordered_map<std::string, std::vector<TypePtr>> constructors_;
    std::vector<std::string> diagnostics_;
    TypePtr expectedReturnType_;
    TypeCheckerOptions options_;

    void pushScope();
    void popScope();
    void bind(const std::string& name, TypePtr type);
    TypePtr lookup(const std::string& name) const;
    void checkStatement(Stmt* statement);
    void checkDeclaration(Decl* declaration);
    void checkFunction(FunctionDecl& function);
    TypePtr inferExpression(Expr* expression);
    TypePtr resolveType(const TypePtr& type) const;
    TypePtr evaluateType(
        const TypePtr& type,
        const std::unordered_map<std::string, TypePtr>& substitutions = {}) const;
    TypePtr propertyType(const TypePtr& object, const std::string& property) const;
    TypePtr substituteType(
        const TypePtr& type,
        const std::unordered_map<std::string, TypePtr>& substitutions) const;
    void inferTypeArguments(
        const TypePtr& pattern, const TypePtr& actual,
        const std::vector<std::string>& typeParameters,
        std::unordered_map<std::string, TypePtr>& substitutions) const;
    bool isAssignable(const TypePtr& source, const TypePtr& target) const;
    TypePtr narrowTypeForCondition(
        const TypePtr& original, const Expr* condition,
        const std::string& variable, bool whenTrue) const;
    void validateTypeArguments(const TypePtr& type, const ASTNode& node);
    static TypePtr unionOf(std::vector<TypePtr> types);
    static bool sameType(const TypePtr& left, const TypePtr& right);
    void report(const ASTNode& node, const std::string& code,
                const std::string& message);
    static TypePtr makeType(Type::Kind kind, const std::string& name = "");
    static std::string typeName(const TypePtr& type);
};

// Parse `// @option` compiler directives from the leading comments of a source
// file into a TypeCheckerOptions. Defined in TypeChecker.cpp.
TypeCheckerOptions parseCompilerDirectives(const std::string& source);

} // namespace nova
